[build]
  command = "npm run build"
  publish = "build"

# Let /admin work on a single-page host
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# SPA fallback - only for routes that don't have file extensions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false