backend:
  name: git-gateway
  branch: main

locale: fr

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

display_url: https://dtrimajibe.com
logo_url: https://dtrimajibe.com/favicon.ico

collections:
  - name: "blog"
    label: "Articles de Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: "Titre", widget: string }
      - { name: date, label: "Date", widget: datetime }
      - { name: author, label: "Auteur", widget: string, default: "Dt. Rim Ajibe" }
      - { name: tags, label: "Mots-clés", widget: list }
      - { name: excerpt, label: "Résumé", widget: text }
      - { name: featured_image, label: "Image principale", widget: image, required: false }
      - { name: body, label: "Contenu", widget: markdown }
      
  - name: "resources"
    label: "Ressources"
    folder: "content/resources"
    create: true
    extension: json
    fields:
      - { name: title, label: "Nom", widget: string }
      - { name: description, label: "Description", widget: text }
      - name: category
        label: "Catégorie"
        widget: select
        options:
          - { label: "Guides Nutrition", value: "guides-nutrition" }
          - { label: "Nutrition Sportive", value: "nutrition-sportive" }
          - { label: "Gestion du Poids", value: "gestion-poids" }
          - { label: "Nutrition Thérapeutique", value: "nutrition-therapeutique" }
          - { label: "Outils Pratiques", value: "outils-pratiques" }
          - { label: "E-books", value: "ebooks" }
      - { name: file, label: "Fichier", widget: file }
      - { name: file_size, label: "Taille du fichier", widget: string, required: false }
      - { name: pages, label: "Nombre de pages", widget: number, required: false }